# Generated by Django 6.0.8 on 2026-09-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_blog', '0067_rename_blog_categories_blogentrypage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='posts_per_page',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Entries per page'),
        ),
    ]
