# Generated by Django 6.0.8 on 2026-09-11 10:08

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_blog', '0068_index_page_field_labels'),
        ('sites_conformes_core', '0086_index_page_filter_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='filter_categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Parent categories to use as filter groups. Leave empty to list every category in use.', limit_choices_to={'children__isnull': False}, to='sites_conformes_core.category', verbose_name='Category groups'),
        ),
    ]
