# Generated by Django 5.1.7 on 2025-04-01 14:40

from django.db import migrations

from sites_conformes.core import without_swapped_relations


class Migration(migrations.Migration):

    dependencies = [
        ("sites_conformes_forms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formfield",
            options={"ordering": ["sort_order"], "verbose_name": "Form field", "verbose_name_plural": "Form fields"},
        ),
    ]
    # A swapped project declares its own form fields model (see AbstractFormPage)
    operations = without_swapped_relations(operations, "SF_FORMPAGE_MODEL", ("formfield",))
