# Generated by Django 6.0.8 on 2026-09-11 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_events', '0038_rename_event_categories_evententrypage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsindexpage',
            name='filter_by_source',
            field=models.BooleanField(default=False, help_text='The source is the organization of the post author', verbose_name='Filter by source'),
        ),
        migrations.AlterField(
            model_name='eventsindexpage',
            name='posts_per_page',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Entries per page'),
        ),
    ]
