# Generated by Django 6.0.8 on 2026-09-11 10:06

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_core', '0084_rename_entries_per_page_catalogindexpage_posts_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogindexpage',
            name='filter_by_category',
            field=models.BooleanField(default=True, verbose_name='Filter by category'),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='sites_conformes_core.category', verbose_name='Categories'),
        ),
    ]
