# Generated by Django 6.0.8 on 2026-09-25 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_core', '0086_index_page_filter_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sites_conformes_core.category', verbose_name='Parent category'),
        ),
    ]
