# Generated by Django 6.0.8 on 2026-09-25 13:30

import django.db.models.deletion
from django.db import migrations, models


def break_cycles(apps, schema_editor):
    """Detach any category whose parent chain loops back on itself: treebeard walks ancestors without a guard."""
    Category = apps.get_model("sites_conformes_core", "Category")
    parents = dict(Category.objects.values_list("pk", "parent_id"))
    for pk in parents:
        seen = set()
        node = pk
        while node is not None and node not in seen:
            seen.add(node)
            node = parents.get(node)
        if node is not None:  # the walk came back to a node already seen: a cycle
            Category.objects.filter(pk=node).update(parent=None)
            parents[node] = None


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_core', '0086_index_page_filter_categories'),
    ]

    operations = [
        migrations.RunPython(break_cycles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sites_conformes_core.category', verbose_name='Parent category'),
        ),
    ]
