# Generated by Django 6.0.8 on 2026-10-09 08:51

from django.db import migrations, models


def number_siblings(apps, schema_editor):
    """Numbers each group of siblings from 1, in the name order they were sorted by until now.

    django-treebeard's adjacency list counts sibling orders from 1: with 0, moving a node
    before another one silently leaves both at the same place.
    """
    Category = apps.get_model("sites_conformes_core", "Category")
    parent_ids = Category.objects.values_list("parent_id", flat=True).distinct()
    for parent_id in parent_ids:
        siblings = Category.objects.filter(parent_id=parent_id).order_by("name", "pk")
        for sib_order, category in enumerate(siblings, start=1):
            Category.objects.filter(pk=category.pk).update(sib_order=sib_order)


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_core', '0087_category_parent_cascade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sib_order'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='sib_order',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(number_siblings, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
    ]
