# Generated by Django 6.0.5 on 2026-06-09 19:57

from django.db import migrations

def copy_images(apps, schema_editor):
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("sites_conformes_customimages", "CustomImage")
    for image in OldImage.objects.all():
        NewImage.objects.create(
            id=image.id,
            title=image.title,
            file=image.file,
            width=image.width,
            height=image.height,
            created_at=image.created_at,
            uploaded_by_user=image.uploaded_by_user,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_customimages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_images, migrations.RunPython.noop),
    ]
