# Generated by Django 6.0.5 on 2026-06-09 19:57

from django.db import migrations


def copy_images(apps, schema_editor):
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("sites_conformes_customimages", "CustomImage")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    # On copie tous les champs concrets définis par AbstractImage plutôt qu'une
    # liste choisie à la main, pour ne rien perdre silencieusement (collection,
    # focal_point_*, file_size/file_hash, description...) si le modèle de base
    # gagne des champs plus tard. On exclut les ManyToMany/relations inverses ;
    # les tags sont traités séparément ci-dessous car le TaggableManager de
    # taggit n'est pas disponible sur les modèles historiques.
    copy_fields = [
        f.name for f in OldImage._meta.get_fields() if f.concrete and not f.many_to_many and f.name != "id"
    ]

    old_content_type = ContentType.objects.get_for_model(OldImage)
    new_content_type = ContentType.objects.get_for_model(NewImage)

    for image in OldImage.objects.all():
        NewImage.objects.update_or_create(
            id=image.id,
            defaults={field: getattr(image, field) for field in copy_fields},
        )
        old_tags = TaggedItem.objects.filter(content_type=old_content_type, object_id=image.id)
        for tagged_item in old_tags:
            TaggedItem.objects.update_or_create(
                tag_id=tagged_item.tag_id,
                content_type=new_content_type,
                object_id=image.id,
            )

    # Réaligne la séquence d'auto-incrément sur le max(id) copié
    from django.db import connection

    table = NewImage._meta.db_table
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM {table}), 1))"
        )


def reverse_copy_images(apps, schema_editor):
    # Supprime uniquement les CustomImage issues de la copie (mêmes ids que les
    # images d'origine) et leurs tags, pour un rollback propre sans toucher aux
    # images éventuellement créées après la migration.
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("sites_conformes_customimages", "CustomImage")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    copied_ids = list(OldImage.objects.values_list("id", flat=True))
    new_content_type = ContentType.objects.get_for_model(NewImage)
    TaggedItem.objects.filter(content_type=new_content_type, object_id__in=copied_ids).delete()
    NewImage.objects.filter(id__in=copied_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_customimages', '0001_initial'),
        ('wagtailimages', '__latest__'),
        ('taggit', '__latest__'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(copy_images, reverse_copy_images),
    ]
